[20:02:34][INFO][Thread-1][ProcessTaskEngine][processRequest] - Pool size is 0
[20:02:34][INFO][Thread-3][ProcessingTaskGeneco][run] - --> thread started for socket = Socket[addr=/127.0.0.1,port=58586,localport=40002]
[20:02:34][INFO][Thread-3][ProcessingTaskGeneco][run] - ------------------------------------request start--------------------------------------------------
[20:02:34][INFO][Thread-3][ProcessingTaskGeneco][run] - request from address: 127.0.0.1 port: 58586
[20:02:34][INFO][Thread-3][ProcessingTaskGeneco][run] - poruja: 5C72375600002EB900001702090F00050A76158C04BC18F0003600310010FFFF00012C000000000000000B51532B060B51532B640000AD
[20:02:34][INFO][Thread-3][ProcessingTaskGeneco][run] - PArsed Message, gps_message = *Uredjaj: 11961, _serialNumber: null, kartica: null, Alarm: null,_tempSpeed = 100.00800000000001, Status: null, Napon: 30.0, Fix: A, Latituda: 44.64252666666667 null, Longituda: 20.21064 null, _gpsLatNonFormated: 4438.5516, _gpsLongNonFormated: 2012.6384, Brzina: 0.0, Smer: 49.0, Tip poruke: GENECO, Pozicija: 0 km od , , , , Vreme: 2023-02-09 16:00:05
[20:02:36][ERROR][Thread-3][ProcessingTaskGeneco][run] - Unable to insert gps data from vehicle in database, details: Couldn't connect to database.
java.lang.Exception: Couldn't connect to database.
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:125)
	at yu.co.certus.pos.lanus.concurrent.ProcessingTaskGeneco.run(ProcessingTaskGeneco.java:136)
	at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:743)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:136)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:116)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:369)
	at org.postgresql.Driver.connect(Driver.java:245)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:99)
	... 3 more
Caused by: java.net.UnknownHostException: null
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:195)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at java.net.Socket.<init>(Socket.java:375)
	at java.net.Socket.<init>(Socket.java:189)
	at org.postgresql.core.PGStream.<init>(PGStream.java:58)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77)
	... 12 more
[20:02:36][INFO][Thread-3][ProcessingTaskGeneco][run] - poruja: 5C723700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[20:02:36][INFO][Thread-3][ProcessingTaskGeneco][run] - <-- thread finished, all resources closed
[20:03:53][INFO][Thread-1][ProcessTaskEngine][processRequest] - Pool size is 0
[20:03:53][INFO][Thread-4][ProcessingTaskGeneco][run] - --> thread started for socket = Socket[addr=/127.0.0.1,port=58649,localport=40002]
[20:03:53][INFO][Thread-4][ProcessingTaskGeneco][run] - ------------------------------------request start--------------------------------------------------
[20:03:53][INFO][Thread-4][ProcessingTaskGeneco][run] - request from address: 127.0.0.1 port: 58649
[20:03:53][INFO][Thread-4][ProcessingTaskGeneco][run] - poruja: 5C72375600002EB900001702090F00050A76158C04BC18F0003600310010FFFF00012C000000000000000B51532B060B51532B640000AD
[20:03:53][INFO][Thread-4][ProcessingTaskGeneco][run] - PArsed Message, gps_message = *Uredjaj: 11961, _serialNumber: null, kartica: null, Alarm: null,_tempSpeed = 100.00800000000001, Status: null, Napon: 30.0, Fix: A, Latituda: 44.64252666666667 null, Longituda: 20.21064 null, _gpsLatNonFormated: 4438.5516, _gpsLongNonFormated: 2012.6384, Brzina: 0.0, Smer: 49.0, Tip poruke: GENECO, Pozicija: 0 km od , , , , Vreme: 2023-02-09 16:00:05
[20:03:56][ERROR][Thread-4][ProcessingTaskGeneco][run] - Unable to insert gps data from vehicle in database, details: Couldn't connect to database.
java.lang.Exception: Couldn't connect to database.
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:125)
	at yu.co.certus.pos.lanus.concurrent.ProcessingTaskGeneco.run(ProcessingTaskGeneco.java:136)
	at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:743)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:136)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:116)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:369)
	at org.postgresql.Driver.connect(Driver.java:245)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:99)
	... 3 more
Caused by: java.net.UnknownHostException: null
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:195)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at java.net.Socket.<init>(Socket.java:375)
	at java.net.Socket.<init>(Socket.java:189)
	at org.postgresql.core.PGStream.<init>(PGStream.java:58)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77)
	... 12 more
[20:03:56][INFO][Thread-4][ProcessingTaskGeneco][run] - poruja: 5C723700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[20:03:56][INFO][Thread-4][ProcessingTaskGeneco][run] - <-- thread finished, all resources closed
[20:04:26][INFO][Thread-1][ProcessTaskEngine][processRequest] - Pool size is 0
[20:04:26][INFO][Thread-5][ProcessingTaskGeneco][run] - --> thread started for socket = Socket[addr=/127.0.0.1,port=58661,localport=40002]
[20:04:26][INFO][Thread-5][ProcessingTaskGeneco][run] - ------------------------------------request start--------------------------------------------------
[20:04:26][INFO][Thread-5][ProcessingTaskGeneco][run] - request from address: 127.0.0.1 port: 58661
[20:04:26][INFO][Thread-5][ProcessingTaskGeneco][run] - poruja: 5C72375600002EB900001702090F00050A76158C04BC18F0003600310010FFFF00012C000000000000000B51532B060B51532B640000AD
[20:04:26][INFO][Thread-5][ProcessingTaskGeneco][run] - PArsed Message, gps_message = *Uredjaj: 11961, _serialNumber: null, kartica: null, Alarm: null,_tempSpeed = 100.00800000000001, Status: null, Napon: 30.0, Fix: A, Latituda: 44.64252666666667 null, Longituda: 20.21064 null, _gpsLatNonFormated: 4438.5516, _gpsLongNonFormated: 2012.6384, Brzina: 0.0, Smer: 49.0, Tip poruke: GENECO, Pozicija: 0 km od , , , , Vreme: 2023-02-09 16:00:05
[20:04:29][ERROR][Thread-5][ProcessingTaskGeneco][run] - Unable to insert gps data from vehicle in database, details: Couldn't connect to database.
java.lang.Exception: Couldn't connect to database.
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:125)
	at yu.co.certus.pos.lanus.concurrent.ProcessingTaskGeneco.run(ProcessingTaskGeneco.java:136)
	at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:743)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:136)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:116)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:369)
	at org.postgresql.Driver.connect(Driver.java:245)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at yu.co.certus.pos.geneco.data.PostGreAgent.<init>(PostGreAgent.java:99)
	... 3 more
Caused by: java.net.UnknownHostException: null
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:195)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at java.net.Socket.<init>(Socket.java:375)
	at java.net.Socket.<init>(Socket.java:189)
	at org.postgresql.core.PGStream.<init>(PGStream.java:58)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77)
	... 12 more
[20:04:29][INFO][Thread-5][ProcessingTaskGeneco][run] - poruja: 5C723700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[20:04:29][INFO][Thread-5][ProcessingTaskGeneco][run] - <-- thread finished, all resources closed
